[Problem 1] Matrix product is calculated manually

[Problem 1] Matrix product is calculated manually Solve the matrix product of A and B by hand.

In [3]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [8]:
a_ndarray

array([[-1,  2,  3],
       [ 4, -5,  6],
       [ 7,  8, -9]])

In [9]:
b_ndarray

array([[ 0,  2,  1],
       [ 0,  2, -8],
       [ 2,  9, -1]])

In [10]:
ab_mult = np.zeros((a_ndarray.shape[0], b_ndarray.shape[1]))

In [11]:
for i in range(a_ndarray.shape[0]):
    for j in range(b_ndarray.shape[1]):
        ab_mult[i, j] = np.sum(a_ndarray[i, :]*b_ndarray[:, j])

ab_mult

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

In [ ]:
# The above code shows matrix multiplication.

#Given two matrices A and B, the number of columns in matrix A must be equal to the number of rows in matrix B in order for the multiplication to be defined.
#To find the element C i,j in the resulting matrix C at the i-th row and j-th column, you multiply each element in the i-th row of matrix A by the corresponding element in the j-th column of matrix B, and then sum the products.
#Mathematically, the element cij is calculated as:
# C [i,j] = a[i1]*b[j1] + a[i2]*b[j2] + ... + a[in]*b[jn]

[Problem 2] Calculation by NumPy function This matrix product of NumPy can be easily calculated using np.matmul() or np.dot() , or the @ operator.

In [1]:
import numpy as np
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
c_ndarray = np.dot(a_ndarray, b_ndarray)
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [2]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
c_ndarray = np.matmul(a_ndarray, b_ndarray)
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [3]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
c_ndarray = a_ndarray@b_ndarray
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


[Problem 3] Implementation of calculation of a certain element When doing the calculations by hand, you may have first paid attention to row 0 of matrix A and column 0 of matrix B, and then performed the following calculations.

In [12]:
a = a_ndarray
b = b_ndarray
ab_mult = np.zeros((a.shape[0], b.shape[1]))

for i in range(a.shape[0]):
    for j in range(b.shape[1]):
        for k in range(b.shape[0]):
            ab_mult[i][j] += a[i][k] * b[k][j]

ab_mult


array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

[Problem 4] Creating a function that performs matrix multiplication Extend the code in Problem 3 to complete the matrix product scratch implementation. It should be a function that takes matrices A and B as arguments and returns the matrix product.

In [13]:
def matrix_multiplication(a, b):

    ## TODO comment

    assert a.shape[0]==b.shape[1], "Matrix dim is not suitable"  #ERROR MSG
    
    ab_mult = np.zeros((a.shape[0], b.shape[1]))
    
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(b.shape[0]):
                ab_mult[i][j] += a[i][k] * b[k][j]

    return ab_mult
        

In [14]:
matrix_multiplication(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

[Problem 5] Judge the input whose calculation is not defined Depending on the implementation method, the function created in Problem 4 may work even if this D and E array is input. In this case, incorrect calculations will be made. Also, even if an error occurs in the middle, a message that is hard to understand why the error occurred is displayed directly.

In [5]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [6]:
matrix_multiplication(d_ndarray, e_ndarray)

NameError: name 'matrix_multiplication' is not defined

In [8]:
try:
    matrix_multiplication(d_ndarray, e_ndarray)
except Exception as e:
    print("Error messege: ", e)

Error messege:  name 'matrix_multiplication' is not defined


In [1]:
def matrix(a,b):
  total=0
  total_1=0
  for i in range(0,len(a)):
    total=total + a[0][i]*b[i][0]
    total_1=total_1 + a[1][i]*b[i][1]
  return total, total_1,
  if a.shape[0]==b.shape[1]:
    return total, total_1, total_2
  else:
    print("Warning")
    return none
print(list(matrix([[-1, 2, 3], [4, -5, 6]],[[-9, 8, 7], [6, -5, 4]])))



[21, 57]


[Problem 6] Transposition Transposing one matrix allows you to calculate the matrix product.

In [15]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print("A, B matrix:")
print(a_ndarray)
print(b_ndarray)
c_ndarray = np.dot(a_ndarray, b_ndarray).T

print("Transposing matrix:")
print(c_ndarray)

A, B matrix:
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]
Transposing matrix:
[[  6  12 -18]
 [ 29  52 -51]
 [-20  38 -48]]
